import type { ChatCompletionRequest, LLMClient, LLMStreamChunk } from '../../llm';
import type { Event } from '../../types';
import { isMessageEvent, isTextContent } from '../../types';

export interface CondensationResult {
  summary: string | null;
  forgottenEventIds: string[];
  summaryOffset: number;
}

export interface LLMSummarizingCondenserOptions {
  keepFirst?: number;
  /**
   * Maximum input tokens budget. Used both to choose which events are forgotten and
   * to clip the summarization prompt (best-effort).
   */
  maxInputTokens: number;
  /**
   * Target fraction of maxInputTokens to retain after condensation (default: 0.5).
   * Mirrors python's `max_size // 2` behavior but in token space.
   */
  targetFraction?: number;
  /**
   * Reserved tokens for the summary message that will be inserted into the view.
   * Since the summary is generated by the LLM, we reserve space conservatively.
   */
  reservedSummaryTokens?: number;
  /**
   * Maximum tokens per serialized event included in the condensation prompt.
   * Helps keep the prompt within budget while still including all forgotten events.
   */
  maxEventTokens?: number;
}

const DEFAULT_KEEP_FIRST = 4;
const DEFAULT_TARGET_FRACTION = 0.5;
const DEFAULT_RESERVED_SUMMARY_TOKENS = 512;
const DEFAULT_MAX_EVENT_TOKENS = 350;

const PROMPT_PREAMBLE = [
  'You are maintaining a context-aware state summary for an interactive agent.',
  'You will be given a list of events corresponding to actions taken by the agent, and the most recent previous summary if one exists.',
  'If the events being summarized contain ANY task-tracking, you MUST include a TASK_TRACKING section to maintain continuity.',
  'When referencing tasks make sure to preserve exact task IDs and statuses.',
  '',
  'Track:',
  '',
  'USER_CONTEXT: (Preserve essential user requirements, goals, and clarifications in concise form)',
  '',
  'TASK_TRACKING: {Active tasks, their IDs and statuses - PRESERVE TASK IDs}',
  '',
  'COMPLETED: (Tasks completed so far, with brief results)',
  'PENDING: (Tasks that still need to be done)',
  'CURRENT_STATE: (Current variables, data structures, or relevant state)',
  '',
  'For code-specific tasks, also include:',
  'CODE_STATE: {File paths, function signatures, data structures}',
  'TESTS: {Failing cases, error messages, outputs}',
  'CHANGES: {Code edits, variable updates}',
  'DEPS: {Dependencies, imports, external calls}',
  'VERSION_CONTROL_STATUS: {Repository state, current branch, PR status, commit history}',
  '',
  'PRIORITIZE:',
  '1. Adapt tracking format to match the actual task type',
  '2. Capture key user requirements and goals',
  '3. Distinguish between completed and pending tasks',
  '4. Keep all sections concise and relevant',
  '',
  'SKIP: Tracking irrelevant details for the current task type',
  '',
  'Example formats:',
  '',
  'For code tasks:',
  'USER_CONTEXT: Fix FITS card float representation issue',
  'COMPLETED: Modified mod_float() in card.py, all tests passing',
  'PENDING: Create PR, update documentation',
  'CODE_STATE: mod_float() in card.py updated',
  'TESTS: test_format() passed',
  'CHANGES: str(val) replaces f"{val:.16G}"',
  'DEPS: None modified',
  'VERSION_CONTROL_STATUS: Branch: fix-float-precision, Latest commit: a1b2c3d',
  '',
  'For other tasks:',
  'USER_CONTEXT: Write 20 haikus based on coin flip results',
  'COMPLETED: 15 haikus written for results [T,H,T,H,T,H,T,T,H,T,H,T,H,T,H]',
  'PENDING: 5 more haikus needed',
  'CURRENT_STATE: Last flip: Heads, Haiku count: 15/20',
].join('\n');

const buildSummarizingPrompt = (params: { previousSummary: string; events: string[] }): string => {
  const parts = [
    PROMPT_PREAMBLE,
    '',
    '<PREVIOUS SUMMARY>',
    params.previousSummary,
    '</PREVIOUS SUMMARY>',
    '',
    ...params.events.flatMap((event) => ['<EVENT>', event, '</EVENT>', '']),
    'Now summarize the events using the rules above.',
  ];
  return parts.join('\n').trim() + '\n';
};

const estimateTokens = (text: string): number => {
  // Simple heuristic: ~4 chars per token (OpenAI guidance). We bias high so budgeting
  // is conservative.
  const chars = text.trim().length;
  if (chars <= 0) return 0;
  return Math.ceil(chars / 4);
};

const clipTextToTokenBudget = (text: string, maxTokens: number): string => {
  if (maxTokens <= 0) return '';
  const estimated = estimateTokens(text);
  if (estimated <= maxTokens) return text;
  const maxChars = Math.max(0, maxTokens * 4);
  if (maxChars <= 1) return '…';
  return text.slice(0, Math.max(0, maxChars - 1)) + '…';
};

const formatMessageEventForPrompt = (event: Extract<Event, { kind: 'MessageEvent' }>): string => {
  const role = event.llm_message.role;
  const text = event.llm_message.content
    .filter(isTextContent)
    .map((part) => part.text)
    .join(' ')
    .trim();

  const preview = clipTextToTokenBudget(text || '[no text content]', 200);
  return `MessageEvent (${event.source})\n  ${role}: ${preview}`;
};

const getMessageEvents = (events: Event[]): Array<Extract<Event, { kind: 'MessageEvent' }>> =>
  events.filter(isMessageEvent);

export class LLMSummarizingCondenser {
  constructor(private readonly llm: LLMClient, private readonly options: LLMSummarizingCondenserOptions) {}

  async condense(params: { events: Event[]; previousSummary?: string }): Promise<CondensationResult | undefined> {
    const keepFirst = Math.max(0, Math.trunc(this.options.keepFirst ?? DEFAULT_KEEP_FIRST));
    const maxInputTokens = Math.max(0, Math.trunc(this.options.maxInputTokens));
    if (maxInputTokens <= 0) return undefined;

    const targetFraction =
      typeof this.options.targetFraction === 'number' && Number.isFinite(this.options.targetFraction)
        ? Math.min(0.95, Math.max(0.05, this.options.targetFraction))
        : DEFAULT_TARGET_FRACTION;
    const targetTokens = Math.max(1, Math.floor(maxInputTokens * targetFraction));

    const reservedSummaryTokens = Math.max(
      0,
      Math.trunc(this.options.reservedSummaryTokens ?? DEFAULT_RESERVED_SUMMARY_TOKENS),
    );

    const messageEvents = getMessageEvents(params.events);
    if (messageEvents.length <= keepFirst + 1) return undefined;

    const serialized = messageEvents.map((event) => ({
      id: event.id ?? '',
      text: formatMessageEventForPrompt(event),
    }));
    if (serialized.some((entry) => !entry.id)) return undefined;

    const head = serialized.slice(0, keepFirst);
    const headTokens = head.reduce((sum, entry) => sum + estimateTokens(entry.text), 0);
    const budgetForTail = Math.max(0, targetTokens - headTokens - reservedSummaryTokens);

    let tailStart = serialized.length;
    let tailTokens = 0;
    for (let i = serialized.length - 1; i >= keepFirst; i -= 1) {
      const t = estimateTokens(serialized[i].text);
      if (tailTokens + t > budgetForTail) break;
      tailTokens += t;
      tailStart = i;
    }

    if (tailStart <= keepFirst) return undefined;

    let forgotten = serialized.slice(keepFirst, tailStart);
    if (!forgotten.length) return undefined;

    const maxEventTokens = Math.max(10, Math.trunc(this.options.maxEventTokens ?? DEFAULT_MAX_EVENT_TOKENS));
    let perEventBudget = maxEventTokens;
    let prompt = '';
    let promptTokens = Infinity;

    const previousSummary = params.previousSummary ?? '';
    const build = (events: typeof forgotten): string =>
      buildSummarizingPrompt({
        previousSummary,
        events: events.map((entry) => clipTextToTokenBudget(entry.text, perEventBudget)),
      });

    // Best-effort: shrink per-event budget until prompt fits maxInputTokens.
    for (let i = 0; i < 5; i += 1) {
      prompt = build(forgotten);
      promptTokens = estimateTokens(prompt);
      if (promptTokens <= maxInputTokens) break;
      perEventBudget = Math.max(20, Math.floor(perEventBudget * 0.6));
    }

    // If we still don't fit, drop the oldest forgotten events until we do.
    while (forgotten.length > 1 && promptTokens > maxInputTokens) {
      forgotten = forgotten.slice(1);
      prompt = build(forgotten);
      promptTokens = estimateTokens(prompt);
    }

    if (promptTokens > maxInputTokens) return undefined;

    const request: ChatCompletionRequest = {
      systemPrompt: 'You summarize conversation history for an interactive agent.',
      messages: [{ role: 'user', content: [{ type: 'text', text: prompt }] }],
    };

    const summary = await this.runSummary(request);
    const trimmed = summary.trim();
    return {
      summary: trimmed ? trimmed : null,
      forgottenEventIds: forgotten.map((entry) => entry.id),
      summaryOffset: keepFirst,
    };
  }

  private async runSummary(request: ChatCompletionRequest): Promise<string> {
    let text = '';
    for await (const chunk of this.llm.streamChat(request)) {
      text = this.applyChunk(chunk, text);
    }
    return text;
  }

  private applyChunk(chunk: LLMStreamChunk, current: string): string {
    if (chunk.type === 'text') return current + chunk.text;
    return current;
  }
}
